# Generated by Django 4.2.4 on 2023-10-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='email_code_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verify',
            name='phone_code_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
