# Generated by Django 4.2.4 on 2023-10-03 01:47

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_verify_email_code_expired_verify_phone_code_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='email_code_expired',
            field=models.DateTimeField(default=account.models.CodeExpire),
        ),
        migrations.AlterField(
            model_name='verify',
            name='phone_code_expired',
            field=models.DateTimeField(default=account.models.CodeExpire),
        ),
    ]
