# Generated by Django 4.2.6 on 2024-03-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='online',
        ),
    ]
