# Generated by Django 5.0.3 on 2024-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='media/user'),
        ),
    ]
