# Generated by Django 5.0.3 on 2024-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='for_reset_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='user'),
        ),
    ]
