# Generated by Django 5.0.3 on 2024-05-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_for_reset_pass_alter_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='for_reset_pass',
        ),
        # migrations.AddField(
        #     model_name='verify',
        #     name='for_reset_pass',
        #     field=models.BooleanField(default=False),
        # ),
    ]
