# Generated by Django 5.0.3 on 2024-05-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_user_for_reset_pass_verify_for_reset_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('corporate', 'Corporate')], default='student', max_length=15),
        )
    ]
