# Generated by Django 4.2.4 on 2023-10-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='media/course/thumb')),
                ('free', models.BooleanField(default=False)),
                ('fee', models.IntegerField()),
                ('discount_amount', models.IntegerField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20, null=True)),
            ],
        ),
    ]
