# Generated by Django 5.0.3 on 2024-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_type',
            field=models.CharField(choices=[('OnlineLiveClass', 'Online Live Class'), ('PhysicalClass', 'Physical Class')], default='OnlineLiveClass', max_length=100),
        ),
    ]
