# Generated by Django 5.0.3 on 2024-05-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
