# Generated by Django 5.0.3 on 2024-06-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_class_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='course',
            name='class_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
