# Generated by Django 4.2.4 on 2023-10-16 18:41

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('options', django_jsonform.models.fields.ArrayField(base_field=models.JSONField(), size=None)),
            ],
        ),
    ]
