# Generated by Django 4.2.6 on 2023-12-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Pricing',
        ),
    ]
