# Generated by Django 4.2.6 on 2023-12-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
        ('membership', '0004_rename_membership_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment')),
                ('pricing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.pricing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
