# Generated by Django 4.2.6 on 2023-12-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('premium', models.BooleanField(default=False)),
                ('color', models.CharField(default='#4B5563', max_length=255)),
            ],
        ),
    ]
