# Generated by Django 4.2.6 on 2024-03-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_folder_options_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='color',
        ),
    ]
