# Generated by Django 4.2.6 on 2024-04-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_folder_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='permium',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='pdf'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FilePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permium', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='data.folder')),
            ],
        ),
    ]
