# Generated by Django 4.2.6 on 2024-04-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_file_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepackage',
            old_name='permium',
            new_name='premium',
        ),
    ]
