# Generated by Django 4.2.6 on 2024-04-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_permium_filepackage_premium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filepackage',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='filepackage',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
