# Generated by Django 5.0.3 on 2024-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_filepackage_options_filepackage_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
