# Generated by Django 4.2.6 on 2024-03-17 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen')], default='unseen', max_length=10),
        ),
    ]
