# Generated by Django 5.0.3 on 2024-06-01 09:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='BD'),
            preserve_default=False,
        ),
    ]
