# Generated by Django 4.2.6 on 2023-12-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=255)),
                ('val_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('store_amount', models.FloatField()),
                ('card_type', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=255)),
                ('bank_tran_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('tran_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
