# Generated by Django 4.2.4 on 2023-10-19 15:34

import apps.chat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomid',
            field=models.CharField(default=apps.chat.models.roomid_generate, editable=False, max_length=30, unique=True),
        ),
    ]
